title: Gureuso's tech blog
email: wyun13043@gmail.com
description: >
  If really love what you do, then the rest follows
baseurl: ""
url: "https://gureuso.github.io"
timezone: Asia/Seoul

# build
markdown: kramdown
gems:
  - jekyll-feed
exclude: ["Gemfile", "Gemfile.lock"]
permalink: /:year/:month/:day/:title/

asset_url: /assets
keep_files: ["assets", "files"]

github:
  username:  gureuso
