title: Gureuso's tech blog
email: wyun13043@gmail.com
description: >
  즐겁게 일하자!
baseurl: ""
url: "nicely.me"
timezone: Asia/Seoul

# build
markdown: kramdown
gems:
  - jekyll-feed
exclude: ["Gemfile", "Gemfile.lock"]
permalink: /:year/:month/:day/:title/

asset_url: /assets
keep_files: ["assets", "files"]

twitter:
  username: wyun13043
github:
  username:  wyun13043