title: 구르소 기술 블로그
email: wyun13043@gmail.com
description: >
  If really love what you do, then the rest follows
baseurl: ""
url: "https://tech.gureuso.me"
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude: ["Gemfile", "Gemfile.lock"]
asset_url: /assets
keep_files: ["assets", "files"]

github:
  username:  gureuso

paginate: 5
paginate_path: "/pages/:num/"